[alembic]
script_location = alembic
prepend_sys_path = .
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(rev)s_%%(slug)s
{% if cookiecutter.database == "postgres" -%}
sqlalchemy.url = postgresql+asyncpg://{{ cookiecutter.package_name }}:secret@db:5432/{{ cookiecutter.package_name }}
{%- elif cookiecutter.database == "mariadb" -%}
sqlalchemy.url = mysql+aiomysql://{{ cookiecutter.package_name }}:secret@db:3306/{{ cookiecutter.package_name }}
{%- elif cookiecutter.database == "sqlite" -%}
sqlalchemy.url = sqlite+aiosqlite:///./{{ cookiecutter.package_name }}.db
{%- endif %}

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
