name: Publish to TestPyPI

on:
  push:
    tags: ['v*']     # v0.1.3-rc1
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: testpypi   # tu publisher lo exige
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install build
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@v1.12.2
        with:
          repository-url: https://test.pypi.org/legacy/
