name: Publish to (Test)PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # Solo si definiste environments en los publishers:
    environment: ${{ contains(github.ref_name, '-rc') && 'testpypi' || 'pypi' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tool
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build artifacts
        run: python -m build

      - name: Publish (OIDC)
        uses: pypa/gh-action-pypi-publish@v1.12.2
        with:
          repository-url: ${{ contains(github.ref_name, '-rc') && 'https://test.pypi.org/legacy/' || '' }}
