name: Publish (main → PyPI)

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'              # ej: v0.1.6
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write        # OIDC / Trusted Publishing

jobs:
  build:
    if: github.ref_type == 'tag' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build
        run: python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish-pypi:
    needs: build
    if: github.ref_type == 'tag' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.12.2
        with:
          # Sin repository-url => PyPI oficial
          skip-existing: true
